// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System.Reflection;
[assembly: AssemblyVersion("140.661")]
[assembly: AssemblyFileVersion("140.661")]
[assembly: AssemblyInformationalVersion("140.661+47b63417")]
